### ISSUE TITLE
[create] failed to sync git repo: exit status 128

### ISSUE THREAD

**Issue by dgroup** [g4s8/gitstrap#38] opened 2019-12-01 15:07 UTC
```bash
 $ ~/gitstrap/gitstrap -debug -version
gitstrap version: 0.2.6151
commit hash: 1468aa1cf49c08c31ae9f331f3331445e390c33f
build date: 2019-09-30T20:33:11Z
18:09:03 $ uname -a
Linux XXX 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
...
```
The command `gitstrap -token=xxx -debug create` creates the repo, however fails with error
```bash
17:56:01 prj $ ~/gitstrap/gitstrap -token=xxx -debug create
2019/12/01 17:56:45 token: ***xxx
strap = create={ctx={debug=true, cfg=&{Gitstrap:0xc00000e680}}}
2019/12/01 17:56:45 [GH] >>> GET https://api.github.com/user
2019/12/01 17:56:45 [GH] https://api.github.com/user <<< 200
2019/12/01 17:56:45 {"login":"dgroup","id":1651114,"node_id":"yyy=","avatar_url":"https://avatars0.githubusercontent.com/u/1651114?v=4","gravatar_id":"","url":"https://api.github.com/users/dgroup","html_url":"https://github.com/dgroup","followers_url":"https://api.github.com/users/dgroup/followers","following_url":"https://api.github.com/users/dgroup/following{/other_user}","gists_url":"https://api.github.com/users/dgroup/gists{/gist_id}","starred_url":"https://api.github.com/users/dgroup/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dgroup/subscriptions","organizations_url":"https://api.github.com/users/dgroup/orgs","repos_url":"https://api.github.com/users/dgroup/repos","events_url":"https://api.github.com/users/dgroup/events{/privacy}","received_events_url":"https://api.github.com/users/dgroup/received_events","type":"User","site_admin":false,"name":"Yurii Dubinka","company":null,"blog":"","location":"Hyderabad","email":"yurii.dubinka@gmail.com","hireable":true,"bio":null,"public_repos":32,"public_gists":9,"followers":19,"following":7,"created_at":"2012-04-17T08:48:20Z","updated_at":"2019-12-01T14:19:14Z"}
RUN: as dgroup options = map[]
Looking up for repo dgroup/c
2019/12/01 17:56:45 [GH] >>> GET https://api.github.com/repos/dgroup/c
2019/12/01 17:56:46 [GH] https://api.github.com/repos/dgroup/c <<< 404
2019/12/01 17:56:46 {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#get"}
repository doesn't exist. Create? (y/n): y
creating repo: dgroup/c
        github.Repository{Name:"c", Description:"zzz", Private:true}
2019/12/01 17:56:51 [GH] >>> POST https://api.github.com/user/repos
2019/12/01 17:56:51 {"name":"c","description":"zzz","private":true}
2019/12/01 17:56:53 [GH] https://api.github.com/user/repos <<< 201
2019/12/01 17:56:53 {"id":225179076,"node_id":"xxxx=","name":"c","full_name":"dgroup/c","private":true,"owner":{"login":"dgroup","id":1651114,"node_id":"xxx","avatar_url":"https://avatars0.githubusercontent.com/u/1651114?v=4","gravatar_id":"","url":"https://api.github.com/users/dgroup","html_url":"https://github.com/dgroup","followers_url":"https://api.github.com/users/dgroup/followers","following_url":"https://api.github.com/users/dgroup/following{/other_user}","gists_url":"https://api.github.com/users/dgroup/gists{/gist_id}","starred_url":"https://api.github.com/users/dgroup/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/dgroup/subscriptions","organizations_url":"https://api.github.com/users/dgroup/orgs","repos_url":"https://api.github.com/users/dgroup/repos","events_url":"https://api.github.com/users/dgroup/events{/privacy}","received_events_url":"https://api.github.com/users/dgroup/received_events","type":"User","site_admin":false},"html_url":"https://github.com/dgroup/c","description":"xxx","fork":false,"url":"https://api.github.com/repos/dgroup/c","forks_url":"https://api.github.com/repos/dgroup/c/forks","keys_url":"https://api.github.com/repos/dgroup/c/keys{/key_id}","collaborators_url":"https://api.github.com/repos/dgroup/c/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/dgroup/c/teams","hooks_url":"https://api.github.com/repos/dgroup/c/hooks","issue_events_url":"https://api.github.com/repos/dgroup/c/issues/events{/number}","events_url":"https://api.github.com/repos/dgroup/c/events","assignees_url":"https://api.github.com/repos/dgroup/c/assignees{/user}","branches_url":"https://api.github.com/repos/dgroup/c/branches{/branch}","tags_url":"https://api.github.com/repos/dgroup/c/tags","blobs_url":"https://api.github.com/repos/dgroup/c/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/dgroup/c/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/dgroup/c/git/refs{/sha}","trees_url":"https://api.github.com/repos/dgroup/c/git/trees{/sha}","statuses_url":"https://api.github.com/repos/dgroup/c/statuses/{sha}","languages_url":"https://api.github.com/repos/dgroup/c/languages","stargazers_url":"https://api.github.com/repos/dgroup/c/stargazers","contributors_url":"https://api.github.com/repos/dgroup/c/contributors","subscribers_url":"https://api.github.com/repos/dgroup/c/subscribers","subscription_url":"https://api.github.com/repos/dgroup/c/subscription","commits_url":"https://api.github.com/repos/dgroup/c/commits{/sha}","git_commits_url":"https://api.github.com/repos/dgroup/c/git/commits{/sha}","comments_url":"https://api.github.com/repos/dgroup/c/comments{/number}","issue_comment_url":"https://api.github.com/repos/dgroup/c/issues/comments{/number}","contents_url":"https://api.github.com/repos/dgroup/c/contents/{+path}","compare_url":"https://api.github.com/repos/dgroup/c/compare/{base}...{head}","merges_url":"https://api.github.com/repos/dgroup/c/merges","archive_url":"https://api.github.com/repos/dgroup/c/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/dgroup/c/downloads","issues_url":"https://api.github.com/repos/dgroup/c/issues{/number}","pulls_url":"https://api.github.com/repos/dgroup/c/pulls{/number}","milestones_url":"https://api.github.com/repos/dgroup/c/milestones{/number}","notifications_url":"https://api.github.com/repos/dgroup/c/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/dgroup/c/labels{/name}","releases_url":"https://api.github.com/repos/dgroup/c/releases{/id}","deployments_url":"https://api.github.com/repos/dgroup/c/deployments","created_at":"2019-12-01T14:56:52Z","updated_at":"2019-12-01T14:56:52Z","pushed_at":"2019-12-01T14:56:53Z","git_url":"git://github.com/dgroup/c.git","ssh_url":"git@github.com:dgroup/c.git","clone_url":"https://github.com/dgroup/c.git","svn_url":"https://github.com/dgroup/c","homepage":null,"size":0,"stargazers_count":0,"watchers_count":0,"language":null,"has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":0,"license":null,"is_template":false,"forks":0,"open_issues":0,"watchers":0,"default_branch":"master","permissions":{"admin":true,"push":true,"pull":true},"allow_squash_merge":true,"allow_merge_commit":true,"allow_rebase_merge":true,"template_repository":null,"network_count":0,"subscribers_count":1}
Github repository c has been created
[create] failed to sync git repo: exit status 128

```

The SSH key was generated and imported to ssh-agent in accordance with https://help.github.com/en/github/authenticating-to-github/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent

The gitstrap template is available here
https://raw.githubusercontent.com/dgroup/gitstrap-templates/master/dgroup-eo-readme.md

**Comment by 0crat** [comment] 2019-12-01 15:07
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2019-12-01 15:07
@dgroup[/z](https://www.0crat.com/u/dgroup) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/CF7JL4282) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by 0crat** [comment] 2019-12-01 15:22
Job [#38](https://github.com/g4s8/gitstrap/issues/38) is now in scope, role is `DEV`

**Comment by g4s8** [comment] 2019-12-01 15:23
@dgroup can you please share your git version? `git --version`

**Comment by 0crat** [comment] 2019-12-01 15:23
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @dgroup[/z](https://www.0crat.com/u/dgroup)

**Comment by dgroup** [comment] 2019-12-01 15:25
@g4s8 
```bash
git --version
git version 2.17.1
```

**Comment by 0crat** [comment] 2019-12-01 15:33
The job [#38](https://github.com/g4s8/gitstrap/issues/38) assigned to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar), here is [why](https://www.0crat.com/footprint/CF7JL4282/89b97f63-8f03-4a80-b9d2-993f04c243e6); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2019-12-06 15:53
@mohamednizar[/z](https://www.0crat.com/u/mohamednizar) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2019-12-11 15:40
The user @mohamednizar[/z](https://www.0crat.com/u/mohamednizar) resigned from [#38](https://github.com/g4s8/gitstrap/issues/38), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by 0crat** [comment] 2019-12-11 15:56
Resigned on delay, see [§8](http://www.zerocracy.com/policy.html#8): -30 point(s) just awarded to @mohamednizar[/z](https://www.0crat.com/u/mohamednizar)

**Comment by 0crat** [comment] 2020-01-26 13:01
The job [#38](https://github.com/g4s8/gitstrap/issues/38) assigned to @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel), here is [why](https://www.0crat.com/footprint/CF7JL4282/93badff3-b725-4ab3-84c7-a1743535d460); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by GnusinPavel** [comment] 2020-01-26 13:17
@dgroup I can success clone this repo
![image](https://user-images.githubusercontent.com/8367459/73135780-56c05880-4057-11ea-9139-d14bb7e058f6.png)
Can you verify that and close the ticket?

**Comment by GnusinPavel** [comment] 2020-01-26 15:20
@dgroup  can't reproduce
```shell
pavel@PavelsMBP test_repo % ../bin/gitstrap -token 6df7f664505270a6f515682495efa3930d294c6c -debug create
2020/01/26 18:15:34 token: ***6df
strap = create={ctx={debug=true, cfg=&{Gitstrap:0xc000020740}}}
2020/01/26 18:15:34 [GH] >>> GET https://api.github.com/user
2020/01/26 18:15:34 [GH] https://api.github.com/user <<< 200
2020/01/26 18:15:34 {"login":"GnusinPavel","id":8367459,"node_id":"MDQ6VXNlcjgzNjc0NTk=","avatar_url":"https://avatars3.githubusercontent.com/u/8367459?v=4","gravatar_id":"","url":"https://api.github.com/users/GnusinPavel","html_url":"https://github.com/GnusinPavel","followers_url":"https://api.github.com/users/GnusinPavel/followers","following_url":"https://api.github.com/users/GnusinPavel/following{/other_user}","gists_url":"https://api.github.com/users/GnusinPavel/gists{/gist_id}","starred_url":"https://api.github.com/users/GnusinPavel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/GnusinPavel/subscriptions","organizations_url":"https://api.github.com/users/GnusinPavel/orgs","repos_url":"https://api.github.com/users/GnusinPavel/repos","events_url":"https://api.github.com/users/GnusinPavel/events{/privacy}","received_events_url":"https://api.github.com/users/GnusinPavel/received_events","type":"User","site_admin":false,"name":"Pavel Gnusin","company":null,"blog":"https://gnusinpavel.github.io","location":"Penza, Russia","email":"pavel.sin.gnusin@gmail.com","hireable":true,"bio":"Software Developer )","public_repos":13,"public_gists":4,"followers":6,"following":10,"created_at":"2014-08-05T20:57:07Z","updated_at":"2020-01-26T14:38:54Z"}
RUN: as GnusinPavel options = map[]
Looking up for repo GnusinPavel/test_repo
2020/01/26 18:15:34 [GH] >>> GET https://api.github.com/repos/GnusinPavel/test_repo
2020/01/26 18:15:34 [GH] https://api.github.com/repos/GnusinPavel/test_repo <<< 404
2020/01/26 18:15:34 {"message":"Not Found","documentation_url":"https://developer.github.com/v3/repos/#get"}
repository doesn't exist. Create? (y/n): y
creating repo: GnusinPavel/test_repo
	github.Repository{Name:"test_repo", Description:"Command line tool to bootstrap Github repository", Private:false}
2020/01/26 18:15:37 [GH] >>> POST https://api.github.com/user/repos
2020/01/26 18:15:37 {"name":"test_repo","description":"Command line tool to bootstrap Github repository","private":false}
2020/01/26 18:15:39 [GH] https://api.github.com/user/repos <<< 201
2020/01/26 18:15:39 {"id":236329816,"node_id":"MDEwOlJlcG9zaXRvcnkyMzYzMjk4MTY=","name":"test_repo","full_name":"GnusinPavel/test_repo","private":false,"owner":{"login":"GnusinPavel","id":8367459,"node_id":"MDQ6VXNlcjgzNjc0NTk=","avatar_url":"https://avatars3.githubusercontent.com/u/8367459?v=4","gravatar_id":"","url":"https://api.github.com/users/GnusinPavel","html_url":"https://github.com/GnusinPavel","followers_url":"https://api.github.com/users/GnusinPavel/followers","following_url":"https://api.github.com/users/GnusinPavel/following{/other_user}","gists_url":"https://api.github.com/users/GnusinPavel/gists{/gist_id}","starred_url":"https://api.github.com/users/GnusinPavel/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/GnusinPavel/subscriptions","organizations_url":"https://api.github.com/users/GnusinPavel/orgs","repos_url":"https://api.github.com/users/GnusinPavel/repos","events_url":"https://api.github.com/users/GnusinPavel/events{/privacy}","received_events_url":"https://api.github.com/users/GnusinPavel/received_events","type":"User","site_admin":false},"html_url":"https://github.com/GnusinPavel/test_repo","description":"Command line tool to bootstrap Github repository","fork":false,"url":"https://api.github.com/repos/GnusinPavel/test_repo","forks_url":"https://api.github.com/repos/GnusinPavel/test_repo/forks","keys_url":"https://api.github.com/repos/GnusinPavel/test_repo/keys{/key_id}","collaborators_url":"https://api.github.com/repos/GnusinPavel/test_repo/collaborators{/collaborator}","teams_url":"https://api.github.com/repos/GnusinPavel/test_repo/teams","hooks_url":"https://api.github.com/repos/GnusinPavel/test_repo/hooks","issue_events_url":"https://api.github.com/repos/GnusinPavel/test_repo/issues/events{/number}","events_url":"https://api.github.com/repos/GnusinPavel/test_repo/events","assignees_url":"https://api.github.com/repos/GnusinPavel/test_repo/assignees{/user}","branches_url":"https://api.github.com/repos/GnusinPavel/test_repo/branches{/branch}","tags_url":"https://api.github.com/repos/GnusinPavel/test_repo/tags","blobs_url":"https://api.github.com/repos/GnusinPavel/test_repo/git/blobs{/sha}","git_tags_url":"https://api.github.com/repos/GnusinPavel/test_repo/git/tags{/sha}","git_refs_url":"https://api.github.com/repos/GnusinPavel/test_repo/git/refs{/sha}","trees_url":"https://api.github.com/repos/GnusinPavel/test_repo/git/trees{/sha}","statuses_url":"https://api.github.com/repos/GnusinPavel/test_repo/statuses/{sha}","languages_url":"https://api.github.com/repos/GnusinPavel/test_repo/languages","stargazers_url":"https://api.github.com/repos/GnusinPavel/test_repo/stargazers","contributors_url":"https://api.github.com/repos/GnusinPavel/test_repo/contributors","subscribers_url":"https://api.github.com/repos/GnusinPavel/test_repo/subscribers","subscription_url":"https://api.github.com/repos/GnusinPavel/test_repo/subscription","commits_url":"https://api.github.com/repos/GnusinPavel/test_repo/commits{/sha}","git_commits_url":"https://api.github.com/repos/GnusinPavel/test_repo/git/commits{/sha}","comments_url":"https://api.github.com/repos/GnusinPavel/test_repo/comments{/number}","issue_comment_url":"https://api.github.com/repos/GnusinPavel/test_repo/issues/comments{/number}","contents_url":"https://api.github.com/repos/GnusinPavel/test_repo/contents/{+path}","compare_url":"https://api.github.com/repos/GnusinPavel/test_repo/compare/{base}...{head}","merges_url":"https://api.github.com/repos/GnusinPavel/test_repo/merges","archive_url":"https://api.github.com/repos/GnusinPavel/test_repo/{archive_format}{/ref}","downloads_url":"https://api.github.com/repos/GnusinPavel/test_repo/downloads","issues_url":"https://api.github.com/repos/GnusinPavel/test_repo/issues{/number}","pulls_url":"https://api.github.com/repos/GnusinPavel/test_repo/pulls{/number}","milestones_url":"https://api.github.com/repos/GnusinPavel/test_repo/milestones{/number}","notifications_url":"https://api.github.com/repos/GnusinPavel/test_repo/notifications{?since,all,participating}","labels_url":"https://api.github.com/repos/GnusinPavel/test_repo/labels{/name}","releases_url":"https://api.github.com/repos/GnusinPavel/test_repo/releases{/id}","deployments_url":"https://api.github.com/repos/GnusinPavel/test_repo/deployments","created_at":"2020-01-26T15:15:37Z","updated_at":"2020-01-26T15:15:37Z","pushed_at":"2020-01-26T15:15:38Z","git_url":"git://github.com/GnusinPavel/test_repo.git","ssh_url":"git@github.com:GnusinPavel/test_repo.git","clone_url":"https://github.com/GnusinPavel/test_repo.git","svn_url":"https://github.com/GnusinPavel/test_repo","homepage":null,"size":0,"stargazers_count":0,"watchers_count":0,"language":null,"has_issues":true,"has_projects":true,"has_downloads":true,"has_wiki":true,"has_pages":false,"forks_count":0,"mirror_url":null,"archived":false,"disabled":false,"open_issues_count":0,"license":null,"forks":0,"open_issues":0,"watchers":0,"default_branch":"master","permissions":{"admin":true,"push":true,"pull":true},"allow_squash_merge":true,"allow_merge_commit":true,"allow_rebase_merge":true,"delete_branch_on_merge":false,"network_count":0,"subscribers_count":1}
Github repository test_repo has been created
Github repository git@github.com:GnusinPavel/test_repo.git has been fetched
Template README.md applied
```

repo creates successfully

**Comment by GnusinPavel** [comment] 2020-01-27 07:59
@0crat wait for @dgroup

**Comment by 0crat** [comment] 2020-01-27 08:01
> @0crat wait for @dgroup  ([here](https://github.com/g4s8/gitstrap/issues/38#issuecomment-578631471))

@GnusinPavel The impediment for [#38](https://github.com/g4s8/gitstrap/issues/38) was registered successfully by @gnusinpavel[/z](https://www.0crat.com/u/gnusinpavel)

**Comment by 0crat** [comment] 2020-08-10 21:05
The job [#38](https://github.com/g4s8/gitstrap/issues/38) assigned to @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry), here is [why](https://www.0crat.com/footprint/CF7JL4282/2f5c3485-88f4-4d23-9ef2-1acbb598d0f4); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-08-15 21:51
@stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by 0crat** [comment] 2020-08-20 21:03
The user @stepanov-dmitry[/z](https://www.0crat.com/u/stepanov-dmitry) resigned from [#38](https://github.com/g4s8/gitstrap/issues/38), please stop working. Reason for job resignation: It is older than 10 days, see [§8](http://www.zerocracy.com/policy.html#8)

**Comment by g4s8** [comment] 2021-03-28 10:59
@dgroup the git usage was removed, now all uploads are performed via GItHub API

**Closed by g4s8** 2021-03-28 10:59 UTC
Labels: bug, scope
